-- Seed data for foods_master and disease_master

-- foods_master
INSERT INTO public.foods_master (rep_code, rep_name, modern_name, name_en, aliases, category, nutrients) VALUES

ON CONFLICT (rep_code) DO NOTHING;

-- disease_master
INSERT INTO public.disease_master (disease, disease_read, disease_alias, disease_alias_read, modern_disease, modern_name_ko, name_en, icd10_code, category, aliases) VALUES
('下血', '하혈', '', '', '자궁 출혈', '자궁 출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('不飢', '불기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('休息痢', '휴식리', '休惜痢', '휴석리', '궤양성 대장염;감염성 만성장관(感染性慢性腸管) Ameba症, 만성 세균성이질(細菌性痢疾)', '궤양성 대장염;감염성 만성장관(感染性慢性腸管) Ameba症, 만성 세균성이질(細菌性痢疾)', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('傷寒初覺', '상한초각', '', '', '감기초기', '감기초기', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('傷寒頭痛', '상한두통', '', '', '감기;두통', '감기;두통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('冷痢', '냉리', '寒痢', '한리', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利大小便', '이대소변', '利大小腸', '이대소장', '변비;소변량 감소;배뇨곤란', '변비;소변량 감소;배뇨곤란', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('去痰下氣', '거담하기', '消痰下氣', '소담하기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('和五藏', '화오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('天行時疾頭痛熱狂', '천행시질두통열광', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('太陽經藥', '태양경약', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('寒疝, 臍腹脹痛, 手不敢近', '한산, 제복창통, 수불감근', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('寒痰', '한담', '冷痰', '냉담', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('小便出血', '소변출혈', '溺血', '요혈', '혈뇨', '혈뇨', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('平胃氣', '평위기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('散風邪', '산풍사', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治血出口鼻如泉涌諸藥不效', '치혈추구비여천용제약불효', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('消痰下氣', '소담하기', '去痰下氣', '거담하기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('溫胃', '온위', '暖胃', '난위', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('疔毒入心嘔逆', '정독입심구역', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('發表', '발표', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肺壅生瘜肉, 不聞香臭', '폐옹생식육, 불문향취', '', '', '후각 상실증', '후각 상실증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾胃冷弱, 腹中刺痛', '비위냉약, 복중자통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('膀胱急妨下水氣', '방광급방하수기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血枯', '혈고', '', '', '무월경', '무월경', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血痢', '혈리', '赤痢', '적리', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血痢尤神效', '혈리우신효', '', '', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('行陽而散氣', '행양이산기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('解表出汗', '해표출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('調和藏府', '조화장부', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('調胃氣', '조위기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('諸痢', '제리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('赤白帶下', '적백대하', '赤白瀝', '적백력', '질분비물', '질분비물', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('赤白痢', '적백리', '注下赤白', '주하적백', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('身熱', '신열', '', '', '발열', '발열', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通大小腸', '통대소장', '滑利大小腸', '활리대소장', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通月經', '통월경', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通陽氣以通上下之陽', '통양기이통상하지양', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開胃', '개위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開腠理出汗', '개주리출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開藏府', '개장부', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('除肝邪氣', '제간사기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('頭痛', '두통', '', '', '두통', '두통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('冷痰', '냉담', '寒痰', '한담', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('便血', '변혈', '', '', '항문출혈', '항문출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久心痛不可忍', '구심통불가인', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('五痔', '오치', '', '', '치질', '치질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('厲氣', '여기', '癘氣', '여기', '병원성 미생물', '병원성 미생물', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('接藥入腎', '접약입신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腸痔下血', '장치하혈', '肛門癰', '항문옹', '내치핵의 감염으로 인하여 항문주위염이 생기거나 탈항된 것', '내치핵의 감염으로 인하여 항문주위염이 생기거나 탈항된 것', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血氣心痛', '혈기심통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補腎中陽氣', '보신중지양기', '補腎陽', '보신양', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利肺氣', '이폐기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('卒失聲', '졸실성', '暴失音', '폭실음', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('榮衛流通血脈調暢', '영위유통혈맥조창', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣滯', '기체', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('聲不出', '성불출', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胸痞痛', '흉비통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾不能消穀', '비불능소곡', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通血脈, 爲百藥之先', '통혈맥, 위백약지선', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養脾', '양비', '補脾', '보비', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('一切蟲', '일체충', '', '', '기생충', '기생충', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('下三焦熱毒氣', '하삼초열독기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('不老', '불로', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('中風失音不語', '중풍실음불어', '', '', '후두염; 발성장애', '후두염; 발성장애', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久痢', '구리', '遷延痢', '천연리', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久赤白痢', '구적백리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('令人有聲', '영인유성', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('咽喉塞', '인후색', '', '', '인두염', '인두염', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('大下氣', '대하기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('小兒噤口痢', '소아금구리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('延年', '연년', '延年益壽', '연년익수', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心痛', '심통', '擧痛', '거통', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('殺諸蟲', '살제충', '', '', '기생충', '기생충', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣虛下痢瘦乏', '기허하리수핍', '', '', '전신쇠약;식욕부진;영양실조;저체중', '전신쇠약;식욕부진;영양실조;저체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治嘔最效', '치구최효', '', '', '구역', '구역', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('熱秘大便不通', '열비대변불통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('産婦因大喜汗出汚衣赤色', '산부인대희한출오의적색', '血汗', '혈한', '색땀증', '색땀증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('痢止', '지리', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癰疽', '옹저', '', '', '농양', '농양', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('發背', '발배', '發背癰', '발배옹', '등쪽 종기증', '등쪽 종기증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肥健人', '비건인', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肥潤五藏', '비윤오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('虛羸', '허리', '', '', '전신쇠약;영양실조;저체중', '전신쇠약;영양실조;저체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('輕身', '경신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('鎭心', '진심', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開咽喉', '개인후', '', '', '인두염', '인두염', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('風熱心煩', '풍열심번', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('骨節風', '골절풍', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('代糧', '대량', '當粮', '당량', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('內傷', '내상', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('平和五藏', '평화오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('暢胃氣', '창위기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('生津液', '생진액', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益精氣', '익정기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('老人虛人皆可服', '노인허인개가복', '', '', '변비', '변비', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('聰利耳目', '총리이목', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補胃氣', '보위기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補養脾胃', '보양비위', '補脾胃', '보비위', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('辟穀', '벽곡', '却粒', '각립', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('駐年', '주년', '延年却老', '연년각로', '노화방지', '노화방지', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('下痢膿血', '하리농혈', '膿血痢', '농혈리', '농혈적 이질', '농혈적 이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久失音', '구실음', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('休粮', '휴량', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('卒心痛', '졸심통', '卒急心痛', '졸급심통', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('吐衄血不止', '노뉵혈부지', '', '', '토혈;비출혈', '토혈;비출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('和脾藥最佳', '화비약최가', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('夢遺', '몽유', '夢泄', '몽설', '몽정', '몽정', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('婦人吐血', '부인토혈', '', '', '토혈', '토혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('實下焦', '실하초', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('小兒血痢', '소아혈리', '血痢', '혈리', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', 'Ameba성 적리(赤痢);궤양성결장염(潰瘍性結腸炎);세균성이질(細菌性痢疾);만성흡혈충병(慢性吸血蟲病)', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('暴失音', '폭실음', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治痢爲最', '치리위최', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('滑脫', '활탈', '', '', '유정', '유정', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤肺', '윤폐', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('澁精氣', '삽정기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('熱泄', '열설', '火泄', '화설', '설사', '설사', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('秘精氣', '비정기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('聲嘶', '성시', '聲嗄', '성애', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('聲瘂', '성아', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾胃虛弱', '비위허약', '脾胃氣虛', '비위기허', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補不足氣', '보부족기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補養元氣', '보양원기', '扶元氣', '부원기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('飮食不進', '음식부진', '少食', '소식', '식욕부진', '식욕부진', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('斷穀不飢', '단곡불기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止痛', '지통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('狂犬咬', '광견교', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('瘧', '학', '瘧疾', '학질', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('解肌發表出汗', '해기발표출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('酒毒', '주독', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('金瘡', '금창', '金刃傷', '금인상', '자상;절상', '자상;절상', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開腠理', '개주리', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('冷泄', '냉설', '寒泄', '한설', '설사', '설사', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('最宜老人', '최의노인', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('濕泄', '습설', '濕瀉', '습사', '설사', '설사', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('臍腹痛', '제복통', '', '', '복통', '복통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止汗', '지한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('盜汗', '도한', '寢汗', '침한', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利大小腸', '이대소장', '滑利大小腸', '활리대소장', '변비;소변량 감소;배뇨곤란', '변비;소변량 감소;배뇨곤란', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('去熱', '거열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('帶下', '대하', '', '', '질분비물', '질분비물', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肺熱氣促', '폐열기촉', '', '', '빈호흡', '빈호흡', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血崩', '혈붕', '', '', '성기 부정 출혈', '성기 부정 출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補肺', '보폐', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('語聲不出', '어성불출', '言語不出', '언어불출', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('健脾消食', '건비소식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利胃', '이위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('延年益壽', '연년익수', '益壽延年', '익수연년', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止泄痢', '지설리', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肺病宜食', '폐병의식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾之穀', '비지곡', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通神明', '통신명', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養脾氣', '양비기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益脾', '익비', '健脾', '건비', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腎虛腰痛', '신허요통', '', '', '요통', '요통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('倒倉法', '도창법', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('停痰瘀血日積月深中宮德不和矣', '', '', '', '편마비;폐결핵;장내기생충질환;간질', '편마비;폐결핵;장내기생충질환;간질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('滋養氣血', '자양기혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補脾', '보비', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補虛益氣', '보허익기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('充肝氣', '충간기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('水穀痢', '수곡리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('白痢', '백리', '白膿痢', '백농리', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腸中淋露', '장중임로', '淋露', '임로', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('除胃中熱', '제위중열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('下氣', '하기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久汗不出', '구한불출', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('散表氣', '표산기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('散表氣出汗', '산표기출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('疏肝氣', '소간기', '疏肝解鬱', '소간해울', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('破積結及膈氣', '파적결급격기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('逆氣', '역기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚氣', '각기', '脚弱', '각약', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('口氣臭', '구기취', '', '', '구취', '구취', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('夜多小便或遺尿', '야다소변혹유뇨', '', '', '야간뇨;요실금', '야간뇨;요실금', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('實表虛', '실표허', '實表', '실표', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('尿管澁痛', '요관삽통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('消化水穀', '소화수곡', '消食', '소식', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('溫脾胃', '온비위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('熱毒', '열독', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益氣', '익기', '補氣', '보기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脈實, 膏粱之人宜服', '맥실, 고량지인의복', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('自汗', '자한', '', '', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('莖中刺痛', '경중자통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久服, 去人脂令人瘦,太肥者可服', '구복, 거인지령인수태, 비자가복', '', '', '비만;과체중', '비만;과체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('令人少睡', '영인소수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('淸利頭目', '청리두목', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('周痺', '주비', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('多睡', '다수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('常欲眠', '상욕면', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤澤腎藏', '윤택신장', '補腎陰', '보신음', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('熱瘧', '열학', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肝家熱', '간가열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胃寒', '위한', '', '', '만성 위염;궤양질환', '만성 위염;궤양질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胃氣', '위기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腎熱', '신열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補肺中陰氣', '보폐중음기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養肝氣', '양간기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('健脾氣', '건비기', '益脾', '익비', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('助十二經脈', '조십이경맥', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('厚腸胃', '후장위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('和脾胃', '화비위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('安中', '안중', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補五藏', '보오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('勞心吐血', '노심토혈', '', '', '토혈', '토혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾病宜食', '비병의식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補益', '보익', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久盜汗', '구도한', '', '', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('手足筋急', '수족근급', '', '', '근경련', '근경련', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('疔腫', '정종', '', '', '농양', '농양', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('發表出汗', '발표출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止吐衄諸血', '지토뉵제혈', '', '', '토혈;비출혈', '토혈;비출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('消瘀血', '소어혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('諸虛吐衄咯血', '제허토뉵각혈', '', '', '토혈;비출혈;각혈', '토혈;비출혈;각혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('降火滋陰', '강화자음', '滋陰降火', '자음강화', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('老虛人上氣咳嗽', '노허인상기해수', '', '', '기침', '기침', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('壯筋骨', '장근골', '長筋骨', '장근골', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('收肺氣', '수폐기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益男子精', '익남자정', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益肺氣', '익폐기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肺中伏火氣欲絶', '폐중복화기욕절', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補腎', '보신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('喉痺熱痛', '후비열통', '喉閉', '후폐', '후두염', '후두염', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('壓撲傷損', '압박상손', '', '', '타박상', '타박상', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('斂肺止喘', '염폐지천', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久服瘦人', '구복수인', '', '', '비만;과체중', '비만;과체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚弱無力', '각약무력', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腎病宜食宜煨常食之', '신병의식의외상식지', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('冷嗽', '냉수', '寒嗽', '한수', '기침', '기침', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('入肝故益筋與血煮', '입간고익근여혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('凡筋病皆治之', '범근병개치지', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('强筋骨', '강근골', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治痰益脾胃', '치담익비위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('消痰', '소담', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('痰唾', '담타', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益筋', '익근', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚氣上衝', '각기상충', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癰毒及疔腫垂死', '옹독급정종수사', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('行十二經脈', '행십이경맥', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤聲喉', '윤성후', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾虛薄食不消化', '비허박식불소화', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('吐衄血', '토뉵혈', '', '', '토혈;비출혈', '토혈;비출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('大能去痰', '대능거담', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('痰血', '담혈', '血痰', '혈담', '혈담', '혈담', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癲狂久不愈', '전광구불유', '', '', '조현증', '조현증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('破惡血', '파악혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('五發癰疽', '오발옹저', '', '', '농양', '농양', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('百種瘡毒', '백종창독', '', '', '일체 체표의 천부(淺部)에 나타나는 외과 질환', '일체 체표의 천부(淺部)에 나타나는 외과 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('久服令人黑瘦枯燥. 肥盛者, 可服', '구복영인흑수고조. 비성자, 가복', '', '', '비만;과체중', '비만;과체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('先下血後大便', '선하혈후대변', '便血', '변혈', '항문출혈', '항문출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('涼心', '양심', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('瘟疫病', '온역병', '', '', '급성 전염질환', '급성 전염질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('能瘦人', '능수인', '', '', '비만;과체중', '비만;과체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚氣水腫', '각기수종', '', '', '부종', '부종', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開心孔', '개심공', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心病宜食', '심병의식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('煩熱少睡', '번열소수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('上中下內外三焦之藥', '상중하내외삼초지약', '補上中下內外三焦之氣', '보상중하내외삼초지기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('充皮膚', '충피부', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('內托陰證瘡瘍必用之藥', '내탁음증창양필용지약', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利益十二經脈血氣', '이익십이경맥혈기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('實衛氣能溫分肉', '실위기능온분육', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('排膿止痛', '배농지통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癰疽久敗瘡', '옹저구패창', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肥腠理', '비주리', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補上中下內外三焦之氣', '보상중하내외삼초지기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補脾養胃', '보비양위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利小便', '이소변', '利水', '이수', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('咽喉痒痛', '인후양통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('失音不語', '실음불어', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心腎交', '심신교', '心腎相交', '심신상교', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('感寒失音', '감한실음', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益心智', '익심지', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('變白髮', '변백발', '變白爲黑', '변백위흑', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('返老還童', '반로위동', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('大小腸大熱', '대소장대열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('小便滑數', '소변활삭', '', '', '잦은 배뇨', '잦은 배뇨', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('小腸熱', '소장열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治血滯小便不利熱淋血淋尤效', '치혈체소변불리열림혈림우효', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('煩躁', '번조', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('健脾', '건비', '益脾', '익비', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('打損', '타손', '跌打損傷', '질타손상', '타박상', '타박상', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('打損瘀血', '타손어혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('塡精髓', '전정수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('斷穀', '단곡', '辟穀', '벽곡', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤五藏', '윤오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('穀積', '곡적', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('耐飢渴', '내기갈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('長生', '장생', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('長肌肉', '장기육', '壯肌肉', '장기육', '영양실조;저체중', '영양실조;저체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('內傷脾腎俱虛', '내상비위구허', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('崩漏', '붕루', '血崩血漏', '혈붕혈루', '여성 성기 부정 출혈', '여성 성기 부정 출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('形容羸瘁', '형용이수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心氣虛損自汗', '심기허손자한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('收斂心液', '수렴심액', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('月水不利', '월수불리', '', '', '과소월경;희발월경', '과소월경;희발월경', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('津液枯竭', '진액고갈', '亡津液', '망진액', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('血積', '혈적', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('上氣', '상기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('塡骨髓', '전골수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('安五藏', '안오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('煖腰膝止痛', '난요슬지통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('痰在脇下非白芥子不能達', '담재협하비백개자불능달', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胸膈痰冷', '흉격담랭', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補血脈', '보혈맥', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補陽氣', '보양기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('噤口痢 ', '금구리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止痢', '지리', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胸中痰飮', '흉중담음', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('鍊五藏滓穢', '연오장재예', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('調理脾胃', '조리비위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('咯血', '각혈', '', '', '각혈', '각혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('好聲', '호성', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('殺狗毒', '쇄구독', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤燥散結', '윤조산결', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('濕氣', '습기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益潤聲氣', '익윤성기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('解肌發汗', '해기발한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('打撲', '타박', '', '', '타박상', '타박상', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('有瘀血痛不可忍', '유어혈통불가인', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('落傷', '낙상', '', '', '낙상', '낙상', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('踠折', '원절', '踒折', '위절', '골절', '골절', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('一切心痛', '일체심통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('一切泄瀉', '일체설사', '', '', '설사', '설사', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('一切風', '일체풍', '諸風', '제풍', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('中風口噤不省', '중풍구금불성', '', '', '급성뇌혈관질환', '급성뇌혈관질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('主屬骨', '주속골', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('吐衄便尿一切失血', '토뉵변뇨일체실혈', '', '', '토혈;비출혈;항문출혈;혈뇨;출혈', '토혈;비출혈;항문출혈;혈뇨;출혈', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('婦人小戶嫁痛', '부인소호가통', '', '', '성교통', '성교통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('專養血, 烏鬚, 黑髮', '전양혈, 오수, 흑발', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心熱', '심열', '心氣熱', '심기열', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止髮白', '지발백', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治盜汗極驗', '치도한극험', '', '', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('痺', '비', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('睡後目赤腫, 須臾漸白, 良久則無', '수후목적종, 수유점백, 양구즉무', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('老瘧', '노학', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('耐寒暑', '내한서', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肝壅', '간옹', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胃中熱痺', '위중열비', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚膝痛痿弱, 不可屈伸', '각슬통위약, 불가굴신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腰脊痛', '요척통', '腰脊重痛', '요척중통', '요통', '요통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('腰腿之疾, 必用藥也', '요퇴지질, 필용약야', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補益精氣', '보익정기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補胃', '보위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補髓', '보수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('變白爲黑', '변백위흑', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('身輕體健', '신경체건', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('長壽', '장수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('陰痿', '음위', '陽萎', '양위', '발기부전', '발기부전', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養肝', '양간', '養血柔肝', '양혈유간', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('黑鬚髮', '흑수발', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('男子泄精', '남자설정', '遺精', '유정', '유정', '유정', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('瘦病', '수병', '', '', '영양실조;저체중', '영양실조;저체중', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益精髓', '익정수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('精敗面黑', '정패면흑', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('神仙', '신선', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('耐老', '내로', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癲癎', '전간', '', '', '간질;열성 경련;달리 분류되지 않은 경련', '간질;열성 경련;달리 분류되지 않은 경련', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('接骨', '접골', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通利五藏', '통리오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('骨折', '골절', '', '', '골절', '골절', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('五色痢', '오색리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('利大腸', '이대장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣痢', '기리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('潤肺養肺', '윤폐양폐', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('酒痢', '주리', '', '', '이질', '이질', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('令人不睡', '영인불수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('明目', '명목', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('昏暗', '혼암', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治肝毒熱', '치간독열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('目赤暗痛', '목적암통', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('靑盲', '청맹', '黑盲', '흑맹', '시신경위축의 말기;황반부변성', '시신경위축의 말기;황반부변성', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('偏正頭痛', '편정두통', '', '', '두통', '두통', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('健脾胃', '건비위', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('出汗', '출한', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('助肝氣', '조간기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('扶元氣', '부원기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('散風', '산풍', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('添膽氣', '첨담기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('生肌肉', '생기육', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益肝膽', '익간담', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾冷氣不和', '비랭기불화', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脾疸', '비달', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補虛損', '보허손', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('進飮食', '진음식', '', '', '식욕촉진', '식욕촉진', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('除濕熱', '제습열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養精神', '양정신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('乳汁絶少', '유즙절소', '乳少', '유소', '유즙분비부전', '유즙분비부전', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('元氣虛乏', '원기허핍', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('內損心肺吐血下血其出如涌泉口鼻皆流須臾不救則死', '내손심폐토혈하혈기출여용천구비개류수유불구즉사', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('卒上氣', '졸상기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('去痰止渴', '거담지갈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('喘急', '천급', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('天行壯熱', '천행장열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('安精神', '안정신', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('定魂魄', '정혼백', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心氣不足', '심기부족', '心氣虛', '심기허', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('日誦千言', '일송천언', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止好唾', '지호타', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('止驚悸', '지경계', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣弱', '기약', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣短', '기단', '氣少', '기소', '천호흡', '천호흡', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣虛', '기허', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣鬱涎盛, 面熱忪悸', '기울연성, 면열종계', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治肺', '치폐', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('治勞補虛', '치로보허', '', '', '전신쇠약;식욕부진', '전신쇠약;식욕부진', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('澁腸', '삽장', '澁腸胃', '삽장위', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('烏鬚髮', '오수발', '黑鬚髮', '흑수발', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('熱瘧煩渴', '열학번갈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益壽延年', '익수연년', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('睡中汗出', '수중한출', '盜汗', '도한', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('精神短少', '정신단소', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('美容顔', '미용안', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肌膚悅澤', '기부열택', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('肺熱', '폐열', '肺氣熱', '폐기열', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胃冷', '위랭', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補上焦元氣', '보상초원기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補五藏氣不足', '보오장기부족', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補肺中陽氣', '보폐중양기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補血虛', '보혈허', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('言語不接', '언어부접', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開心益智令人不忘', '개심익지령인불망', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('開胃消食', '개위소식', '開胃下食', '개위하식', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('風虛眩暈', '풍허현훈', '', '', '어지럼증', '어지럼증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('養肝膽氣', '양간담기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('鳴息', '명식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('不眠', '불면', '不睡', '불수', '불면', '불면', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('去熱毒', '거열독', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心中惡血', '심중악혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('淸心熱', '청심열', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益膽', '익담', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('驚悸', '경계', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('保定肺氣', '보정폐기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('健忘', '건망', '善忘', '선망', '건망', '건망', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('安魂定魄', '안혼정백', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('斷穀止飢', '단곡지기', '斷穀不飢', '단곡불기', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('癲狂', '전광', '', '', '조현증', '조현증', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('不下食', '불하식', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('崩中帶下', '붕중대하', '崩漏帶下', '붕루대하', '월경중간출혈;질분비물', '월경중간출혈;질분비물', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('最止盜汗', '최지도한', '', '', '땀의 이상에 의한 질환', '땀의 이상에 의한 질환', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('月水不調', '월수부조', '月經不順', '월경불순', '생리불순', '생리불순', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('月閉血凝', '월폐혈응', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('去肺中水氣', '거폐중수기', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('强五藏', '강오장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('精魅', '정매', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('脚膝痠痛不得踐地', '각슬산통부득천지', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('心煩', '심번', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('胃痺', '위비', '胸痺', '흉비', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('滋腎補血', '자신보혈', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('益髓塡精', '익수진정', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補腎精', '보신정', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('補腎陰不足', '보신음부족', '補腎陰', '보신음', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('延年不老', '연년불로', '益壽延年', '익수연년', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('氣雄壯', '기웅장', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('通十二經脈', '통십이경맥', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('長筋力', '장근력', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[]),
('令人多睡', '영인다수', '', '', '', '', NULL, NULL, NULL, ARRAY[]::TEXT[])
ON CONFLICT (disease) DO NOTHING;
