-- Rx-Centric v2 migration
-- Assumes existing tables: catalog_drugs, pubmed_papers, tkm_symptom_master, user_prescription_drugs

BEGIN;

-- 1) Add normalized drug FK to extracted prescription items
ALTER TABLE IF EXISTS public.user_prescription_drugs
  ADD COLUMN IF NOT EXISTS drug_entity_id bigint REFERENCES public.catalog_drugs(id);

CREATE INDEX IF NOT EXISTS idx_user_prescription_drugs_drug_entity_id
  ON public.user_prescription_drugs(drug_entity_id);

-- 2) Drug synonyms
CREATE TABLE IF NOT EXISTS public.drug_synonyms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id bigint NOT NULL REFERENCES public.catalog_drugs(id),
  synonym_text text NOT NULL,
  lang text,
  source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_drug_synonyms UNIQUE (drug_id, synonym_text)
);

CREATE INDEX IF NOT EXISTS idx_drug_synonyms_drug_id ON public.drug_synonyms(drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_synonyms_synonym_text ON public.drug_synonyms(synonym_text);

-- 3) MFDS label (or other authoritative label sources)
CREATE TABLE IF NOT EXISTS public.drug_label_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id bigint NOT NULL REFERENCES public.catalog_drugs(id),
  source_name text NOT NULL,
  source_url text,
  efficacy_text text,
  dosage_text text,
  warnings_text text,
  adverse_events_text text,
  contraindications_text text,
  raw_json jsonb,
  trust_level text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_drug_label_sources UNIQUE (drug_id, source_name)
);

CREATE INDEX IF NOT EXISTS idx_drug_label_sources_drug_id ON public.drug_label_sources(drug_id);

-- 4) Drug ↔ PubMed links
CREATE TABLE IF NOT EXISTS public.drug_pubmed_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id bigint NOT NULL REFERENCES public.catalog_drugs(id),
  pmid text NOT NULL REFERENCES public.pubmed_papers(pmid),
  link_type text NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_drug_pubmed_links UNIQUE (drug_id, pmid)
);

CREATE INDEX IF NOT EXISTS idx_drug_pubmed_links_drug_id ON public.drug_pubmed_links(drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_pubmed_links_pmid ON public.drug_pubmed_links(pmid);

-- 5) Symptom token master (bridge layer)
CREATE TABLE IF NOT EXISTS public.symptom_tokens (
  token text PRIMARY KEY,
  label_ko text,
  label_en text,
  category text,
  aliases text[] NOT NULL DEFAULT '{}'::text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 6) Drug ↔ token mapping (efficacy/adverse)
CREATE TABLE IF NOT EXISTS public.drug_symptom_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id bigint NOT NULL REFERENCES public.catalog_drugs(id),
  token text NOT NULL REFERENCES public.symptom_tokens(token),
  token_type text NOT NULL,
  severity_hint text,
  evidence_level text,
  source_ref text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_drug_symptom_tokens UNIQUE (drug_id, token, token_type)
);

CREATE INDEX IF NOT EXISTS idx_drug_symptom_tokens_drug_id ON public.drug_symptom_tokens(drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_symptom_tokens_token ON public.drug_symptom_tokens(token);

-- 7) Token ↔ TKM symptom mapping
CREATE TABLE IF NOT EXISTS public.token_tkm_map (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token text NOT NULL REFERENCES public.symptom_tokens(token),
  tkm_symptom_id bigint NOT NULL REFERENCES public.tkm_symptom_master(id),
  mapping_strength text NOT NULL,
  mapping_type text NOT NULL,
  evidence_note text,
  reviewer text,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_token_tkm_map UNIQUE (token, tkm_symptom_id)
);

CREATE INDEX IF NOT EXISTS idx_token_tkm_map_token ON public.token_tkm_map(token);
CREATE INDEX IF NOT EXISTS idx_token_tkm_map_tkm ON public.token_tkm_map(tkm_symptom_id);

-- 8) Search fallback cache (attribution + trust level)
CREATE TABLE IF NOT EXISTS public.search_fallback_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  provider text,
  url text NOT NULL,
  domain text,
  title text,
  snippet text,
  summary text,
  trust_level text,
  retrieved_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_search_fallback_sources_entity ON public.search_fallback_sources(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_search_fallback_sources_domain ON public.search_fallback_sources(domain);
CREATE INDEX IF NOT EXISTS idx_search_fallback_sources_trust ON public.search_fallback_sources(trust_level);

COMMIT;
