-- =========================
-- Embeddings Table for RAG
-- =========================

CREATE TABLE IF NOT EXISTS public.embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Source Reference
  source_table TEXT NOT NULL,  -- e.g., 'traditional_foods', 'disease_master'
  source_id BIGINT NOT NULL,   -- PK of the source row
  
  -- Content Info
  content_type TEXT NOT NULL,  -- e.g., 'indication', 'summary', 'ingredients'
  content TEXT NOT NULL,       -- Normalized text used for embedding
  
  -- Embedding & Metadata
  embedding vector(1536),      -- OpenAI text-embedding-3-small (1536 dims)
  content_hash TEXT NOT NULL,  -- SHA256 of content (for deduplication)
  model TEXT DEFAULT 'text-embedding-3-small',
  tokens_used INT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicates for same source content
  UNIQUE(source_table, source_id, content_type)
);

-- =========================
-- Indexes
-- =========================

-- For cache lookup (deduplication)
CREATE INDEX IF NOT EXISTS idx_embeddings_hash ON public.embeddings(content_hash);
CREATE INDEX IF NOT EXISTS idx_embeddings_model_hash ON public.embeddings(model, content_hash);

-- For retrieving embeddings by source
CREATE INDEX IF NOT EXISTS idx_embeddings_source ON public.embeddings(source_table, source_id);

-- For actual vector search (HNSW index)
CREATE INDEX IF NOT EXISTS idx_embeddings_vector ON public.embeddings USING hnsw (embedding vector_cosine_ops);
